/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_AssignedChannelId_H_
#define	_AssignedChannelId_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DynamicChannelId.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AssignedChannelId */
typedef DynamicChannelId_t	 AssignedChannelId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AssignedChannelId;
asn_struct_free_f AssignedChannelId_free;
asn_struct_print_f AssignedChannelId_print;
asn_constr_check_f AssignedChannelId_constraint;
ber_type_decoder_f AssignedChannelId_decode_ber;
der_type_encoder_f AssignedChannelId_encode_der;
xer_type_decoder_f AssignedChannelId_decode_xer;
xer_type_encoder_f AssignedChannelId_encode_xer;
per_type_decoder_f AssignedChannelId_decode_uper;
per_type_encoder_f AssignedChannelId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AssignedChannelId_H_ */
