/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#include <asn_internal.h>

#include "AttachUserRequest.h"

static asn_TYPE_member_t asn_MBR_nonStandard_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NonStandardParameter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_nonStandard_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nonStandard_specs_2 = {
	sizeof(struct AttachUserRequest__nonStandard),
	offsetof(struct AttachUserRequest__nonStandard, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonStandard_2 = {
	"nonStandard",
	"nonStandard",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonStandard_tags_2,
	sizeof(asn_DEF_nonStandard_tags_2)
		/sizeof(asn_DEF_nonStandard_tags_2[0]) - 1, /* 1 */
	asn_DEF_nonStandard_tags_2,	/* Same as above */
	sizeof(asn_DEF_nonStandard_tags_2)
		/sizeof(asn_DEF_nonStandard_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_nonStandard_2,
	1,	/* Single element */
	&asn_SPC_nonStandard_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_AttachUserRequest_1[] = {
	{ ATF_POINTER, 1, offsetof(struct AttachUserRequest, nonStandard),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_nonStandard_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonStandard"
		},
};
static int asn_MAP_AttachUserRequest_oms_1[] = { 0 };
static ber_tlv_tag_t asn_DEF_AttachUserRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_AttachUserRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* nonStandard at 268 */
};
static asn_SEQUENCE_specifics_t asn_SPC_AttachUserRequest_specs_1 = {
	sizeof(struct AttachUserRequest),
	offsetof(struct AttachUserRequest, _asn_ctx),
	asn_MAP_AttachUserRequest_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_AttachUserRequest_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	0,	/* Start extensions */
	2	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AttachUserRequest = {
	"AttachUserRequest",
	"AttachUserRequest",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AttachUserRequest_tags_1,
	sizeof(asn_DEF_AttachUserRequest_tags_1)
		/sizeof(asn_DEF_AttachUserRequest_tags_1[0]), /* 1 */
	asn_DEF_AttachUserRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_AttachUserRequest_tags_1)
		/sizeof(asn_DEF_AttachUserRequest_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AttachUserRequest_1,
	1,	/* Elements count */
	&asn_SPC_AttachUserRequest_specs_1	/* Additional specs */
};

