/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_CapabilityID_H_
#define	_CapabilityID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "Key.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CapabilityID_PR {
	CapabilityID_PR_NOTHING,	/* No components present */
	CapabilityID_PR_standardID,
	CapabilityID_PR_nonstandardID
} CapabilityID_PR;

/* CapabilityID */
typedef struct CapabilityID {
	CapabilityID_PR present;
	union CapabilityID_u {
		long	 standardID;
		Key_t	 nonstandardID;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CapabilityID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CapabilityID;

#ifdef __cplusplus
}
#endif

#endif	/* _CapabilityID_H_ */
