/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#include <asn_internal.h>

#include "CapabilitiesNotificationRequest.h"

static asn_TYPE_member_t asn_MBR_nonStandard_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NonStandardParameter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_nonStandard_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nonStandard_specs_5 = {
	sizeof(struct CapabilitiesNotificationRequest__nonStandard),
	offsetof(struct CapabilitiesNotificationRequest__nonStandard, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonStandard_5 = {
	"nonStandard",
	"nonStandard",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonStandard_tags_5,
	sizeof(asn_DEF_nonStandard_tags_5)
		/sizeof(asn_DEF_nonStandard_tags_5[0]) - 1, /* 1 */
	asn_DEF_nonStandard_tags_5,	/* Same as above */
	sizeof(asn_DEF_nonStandard_tags_5)
		/sizeof(asn_DEF_nonStandard_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_nonStandard_5,
	1,	/* Single element */
	&asn_SPC_nonStandard_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CapabilitiesNotificationRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CapabilitiesNotificationRequest, v2NodePresent),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v2NodePresent"
		},
	{ ATF_POINTER, 3, offsetof(struct CapabilitiesNotificationRequest, addList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SeqOfRequestCapabilities,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"addList"
		},
	{ ATF_POINTER, 2, offsetof(struct CapabilitiesNotificationRequest, removeList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SeqOfRequestCapabilities,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"removeList"
		},
	{ ATF_POINTER, 1, offsetof(struct CapabilitiesNotificationRequest, nonStandard),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_nonStandard_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonStandard"
		},
};
static int asn_MAP_CapabilitiesNotificationRequest_oms_1[] = { 1, 2, 3 };
static ber_tlv_tag_t asn_DEF_CapabilitiesNotificationRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CapabilitiesNotificationRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* v2NodePresent at 618 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* addList at 619 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* removeList at 620 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* nonStandard at 621 */
};
static asn_SEQUENCE_specifics_t asn_SPC_CapabilitiesNotificationRequest_specs_1 = {
	sizeof(struct CapabilitiesNotificationRequest),
	offsetof(struct CapabilitiesNotificationRequest, _asn_ctx),
	asn_MAP_CapabilitiesNotificationRequest_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_CapabilitiesNotificationRequest_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CapabilitiesNotificationRequest = {
	"CapabilitiesNotificationRequest",
	"CapabilitiesNotificationRequest",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CapabilitiesNotificationRequest_tags_1,
	sizeof(asn_DEF_CapabilitiesNotificationRequest_tags_1)
		/sizeof(asn_DEF_CapabilitiesNotificationRequest_tags_1[0]), /* 1 */
	asn_DEF_CapabilitiesNotificationRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_CapabilitiesNotificationRequest_tags_1)
		/sizeof(asn_DEF_CapabilitiesNotificationRequest_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CapabilitiesNotificationRequest_1,
	4,	/* Elements count */
	&asn_SPC_CapabilitiesNotificationRequest_specs_1	/* Additional specs */
};

