/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_CapabilityClass_H_
#define	_CapabilityClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CapabilityClass_PR {
	CapabilityClass_PR_NOTHING,	/* No components present */
	CapabilityClass_PR_null,
	CapabilityClass_PR_unsignedMin,
	CapabilityClass_PR_unsignedMax
} CapabilityClass_PR;

/* CapabilityClass */
typedef struct CapabilityClass {
	CapabilityClass_PR present;
	union CapabilityClass_u {
		NULL_t	 null;
		long	 unsignedMin;
		long	 unsignedMax;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CapabilityClass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CapabilityClass;

#ifdef __cplusplus
}
#endif

#endif	/* _CapabilityClass_H_ */
