/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#include <asn_internal.h>

#include "ChannelAttributes.h"

static asn_per_constraints_t asn_PER_type_ChannelAttributes_constr_1 = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_nonStandard_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NonStandardParameter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_nonStandard_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nonStandard_specs_4 = {
	sizeof(struct ChannelAttributes__Static__nonStandard),
	offsetof(struct ChannelAttributes__Static__nonStandard, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonStandard_4 = {
	"nonStandard",
	"nonStandard",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonStandard_tags_4,
	sizeof(asn_DEF_nonStandard_tags_4)
		/sizeof(asn_DEF_nonStandard_tags_4[0]) - 1, /* 1 */
	asn_DEF_nonStandard_tags_4,	/* Same as above */
	sizeof(asn_DEF_nonStandard_tags_4)
		/sizeof(asn_DEF_nonStandard_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_nonStandard_4,
	1,	/* Single element */
	&asn_SPC_nonStandard_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_static_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelAttributes__Static, channelId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StaticChannelId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"channelId"
		},
	{ ATF_POINTER, 1, offsetof(struct ChannelAttributes__Static, nonStandard),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonStandard_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonStandard"
		},
};
static int asn_MAP_static_oms_2[] = { 1 };
static ber_tlv_tag_t asn_DEF_static_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_static_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* channelId at 121 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonStandard at 123 */
};
static asn_SEQUENCE_specifics_t asn_SPC_static_specs_2 = {
	sizeof(struct ChannelAttributes__Static),
	offsetof(struct ChannelAttributes__Static, _asn_ctx),
	asn_MAP_static_tag2el_2,
	2,	/* Count of tags in the map */
	asn_MAP_static_oms_2,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_static_2 = {
	"static",
	"static",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_static_tags_2,
	sizeof(asn_DEF_static_tags_2)
		/sizeof(asn_DEF_static_tags_2[0]) - 1, /* 1 */
	asn_DEF_static_tags_2,	/* Same as above */
	sizeof(asn_DEF_static_tags_2)
		/sizeof(asn_DEF_static_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_static_2,
	2,	/* Elements count */
	&asn_SPC_static_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_nonStandard_10[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NonStandardParameter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_nonStandard_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nonStandard_specs_10 = {
	sizeof(struct ChannelAttributes__userId__nonStandard),
	offsetof(struct ChannelAttributes__userId__nonStandard, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonStandard_10 = {
	"nonStandard",
	"nonStandard",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonStandard_tags_10,
	sizeof(asn_DEF_nonStandard_tags_10)
		/sizeof(asn_DEF_nonStandard_tags_10[0]) - 1, /* 1 */
	asn_DEF_nonStandard_tags_10,	/* Same as above */
	sizeof(asn_DEF_nonStandard_tags_10)
		/sizeof(asn_DEF_nonStandard_tags_10[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_nonStandard_10,
	1,	/* Single element */
	&asn_SPC_nonStandard_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_userId_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelAttributes__userId, joined),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"joined"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelAttributes__userId, userId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UserId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"userId"
		},
	{ ATF_POINTER, 1, offsetof(struct ChannelAttributes__userId, nonStandard),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_nonStandard_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonStandard"
		},
};
static int asn_MAP_userId_oms_7[] = { 2 };
static ber_tlv_tag_t asn_DEF_userId_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_userId_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* joined at 128 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* userId at 130 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* nonStandard at 131 */
};
static asn_SEQUENCE_specifics_t asn_SPC_userId_specs_7 = {
	sizeof(struct ChannelAttributes__userId),
	offsetof(struct ChannelAttributes__userId, _asn_ctx),
	asn_MAP_userId_tag2el_7,
	3,	/* Count of tags in the map */
	asn_MAP_userId_oms_7,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_userId_7 = {
	"userId",
	"userId",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_userId_tags_7,
	sizeof(asn_DEF_userId_tags_7)
		/sizeof(asn_DEF_userId_tags_7[0]) - 1, /* 1 */
	asn_DEF_userId_tags_7,	/* Same as above */
	sizeof(asn_DEF_userId_tags_7)
		/sizeof(asn_DEF_userId_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_userId_7,
	3,	/* Elements count */
	&asn_SPC_userId_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_admitted_17[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_UserId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_admitted_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_admitted_specs_17 = {
	sizeof(struct ChannelAttributes__private__admitted),
	offsetof(struct ChannelAttributes__private__admitted, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_admitted_17 = {
	"admitted",
	"admitted",
	SET_OF_free,
	SET_OF_print,
	SET_OF_constraint,
	SET_OF_decode_ber,
	SET_OF_encode_der,
	SET_OF_decode_xer,
	SET_OF_encode_xer,
	SET_OF_decode_uper,
	SET_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_admitted_tags_17,
	sizeof(asn_DEF_admitted_tags_17)
		/sizeof(asn_DEF_admitted_tags_17[0]) - 1, /* 1 */
	asn_DEF_admitted_tags_17,	/* Same as above */
	sizeof(asn_DEF_admitted_tags_17)
		/sizeof(asn_DEF_admitted_tags_17[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_admitted_17,
	1,	/* Single element */
	&asn_SPC_admitted_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_nonStandard_19[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NonStandardParameter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_nonStandard_tags_19[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nonStandard_specs_19 = {
	sizeof(struct ChannelAttributes__private__nonStandard),
	offsetof(struct ChannelAttributes__private__nonStandard, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonStandard_19 = {
	"nonStandard",
	"nonStandard",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonStandard_tags_19,
	sizeof(asn_DEF_nonStandard_tags_19)
		/sizeof(asn_DEF_nonStandard_tags_19[0]) - 1, /* 1 */
	asn_DEF_nonStandard_tags_19,	/* Same as above */
	sizeof(asn_DEF_nonStandard_tags_19)
		/sizeof(asn_DEF_nonStandard_tags_19[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_nonStandard_19,
	1,	/* Single element */
	&asn_SPC_nonStandard_specs_19	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_private_13[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelAttributes__private, joined),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"joined"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelAttributes__private, channelId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrivateChannelId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"channelId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelAttributes__private, manager),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UserId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"manager"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelAttributes__private, admitted),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_admitted_17,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"admitted"
		},
	{ ATF_POINTER, 1, offsetof(struct ChannelAttributes__private, nonStandard),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_nonStandard_19,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonStandard"
		},
};
static int asn_MAP_private_oms_13[] = { 4 };
static ber_tlv_tag_t asn_DEF_private_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_private_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* joined at 136 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* channelId at 138 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* manager at 139 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* admitted at 140 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* nonStandard at 142 */
};
static asn_SEQUENCE_specifics_t asn_SPC_private_specs_13 = {
	sizeof(struct ChannelAttributes__private),
	offsetof(struct ChannelAttributes__private, _asn_ctx),
	asn_MAP_private_tag2el_13,
	5,	/* Count of tags in the map */
	asn_MAP_private_oms_13,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_private_13 = {
	"private",
	"private",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_private_tags_13,
	sizeof(asn_DEF_private_tags_13)
		/sizeof(asn_DEF_private_tags_13[0]) - 1, /* 1 */
	asn_DEF_private_tags_13,	/* Same as above */
	sizeof(asn_DEF_private_tags_13)
		/sizeof(asn_DEF_private_tags_13[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_private_13,
	5,	/* Elements count */
	&asn_SPC_private_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_nonStandard_24[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NonStandardParameter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_nonStandard_tags_24[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nonStandard_specs_24 = {
	sizeof(struct ChannelAttributes__assigned__nonStandard),
	offsetof(struct ChannelAttributes__assigned__nonStandard, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonStandard_24 = {
	"nonStandard",
	"nonStandard",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonStandard_tags_24,
	sizeof(asn_DEF_nonStandard_tags_24)
		/sizeof(asn_DEF_nonStandard_tags_24[0]) - 1, /* 1 */
	asn_DEF_nonStandard_tags_24,	/* Same as above */
	sizeof(asn_DEF_nonStandard_tags_24)
		/sizeof(asn_DEF_nonStandard_tags_24[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_nonStandard_24,
	1,	/* Single element */
	&asn_SPC_nonStandard_specs_24	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_assigned_22[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelAttributes__assigned, channelId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AssignedChannelId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"channelId"
		},
	{ ATF_POINTER, 1, offsetof(struct ChannelAttributes__assigned, nonStandard),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonStandard_24,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonStandard"
		},
};
static int asn_MAP_assigned_oms_22[] = { 1 };
static ber_tlv_tag_t asn_DEF_assigned_tags_22[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_assigned_tag2el_22[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* channelId at 147 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonStandard at 149 */
};
static asn_SEQUENCE_specifics_t asn_SPC_assigned_specs_22 = {
	sizeof(struct ChannelAttributes__assigned),
	offsetof(struct ChannelAttributes__assigned, _asn_ctx),
	asn_MAP_assigned_tag2el_22,
	2,	/* Count of tags in the map */
	asn_MAP_assigned_oms_22,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_assigned_22 = {
	"assigned",
	"assigned",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_assigned_tags_22,
	sizeof(asn_DEF_assigned_tags_22)
		/sizeof(asn_DEF_assigned_tags_22[0]) - 1, /* 1 */
	asn_DEF_assigned_tags_22,	/* Same as above */
	sizeof(asn_DEF_assigned_tags_22)
		/sizeof(asn_DEF_assigned_tags_22[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_assigned_22,
	2,	/* Elements count */
	&asn_SPC_assigned_specs_22	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ChannelAttributes_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelAttributes, choice.Static),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_static_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"static"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelAttributes, choice.userId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_userId_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"userId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelAttributes, choice.private),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_private_13,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"private"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelAttributes, choice.assigned),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_assigned_22,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"assigned"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ChannelAttributes_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* static at 121 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* userId at 128 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* private at 136 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* assigned at 147 */
};
static asn_CHOICE_specifics_t asn_SPC_ChannelAttributes_specs_1 = {
	sizeof(struct ChannelAttributes),
	offsetof(struct ChannelAttributes, _asn_ctx),
	offsetof(struct ChannelAttributes, present),
	sizeof(((struct ChannelAttributes *)0)->present),
	asn_MAP_ChannelAttributes_tag2el_1,
	4,	/* Count of tags in the map */
	0,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ChannelAttributes = {
	"ChannelAttributes",
	"ChannelAttributes",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_ChannelAttributes_constr_1,
	asn_MBR_ChannelAttributes_1,
	4,	/* Elements count */
	&asn_SPC_ChannelAttributes_specs_1	/* Additional specs */
};

