/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#include <asn_internal.h>

#include "ChannelJoinConfirm.h"

static asn_TYPE_member_t asn_MBR_nonStandard_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NonStandardParameter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_nonStandard_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nonStandard_specs_6 = {
	sizeof(struct ChannelJoinConfirm__nonStandard),
	offsetof(struct ChannelJoinConfirm__nonStandard, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonStandard_6 = {
	"nonStandard",
	"nonStandard",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonStandard_tags_6,
	sizeof(asn_DEF_nonStandard_tags_6)
		/sizeof(asn_DEF_nonStandard_tags_6[0]) - 1, /* 1 */
	asn_DEF_nonStandard_tags_6,	/* Same as above */
	sizeof(asn_DEF_nonStandard_tags_6)
		/sizeof(asn_DEF_nonStandard_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_nonStandard_6,
	1,	/* Single element */
	&asn_SPC_nonStandard_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ChannelJoinConfirm_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelJoinConfirm, result),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Result,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"result"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelJoinConfirm, initiator),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UserId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"initiator"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelJoinConfirm, requested),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChannelId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"requested"
		},
	{ ATF_POINTER, 2, offsetof(struct ChannelJoinConfirm, channelId),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChannelId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"channelId"
		},
	{ ATF_POINTER, 1, offsetof(struct ChannelJoinConfirm, nonStandard),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_nonStandard_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonStandard"
		},
};
static int asn_MAP_ChannelJoinConfirm_oms_1[] = { 3, 4 };
static ber_tlv_tag_t asn_DEF_ChannelJoinConfirm_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ChannelJoinConfirm_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* result at 308 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* initiator at 309 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* requested at 310 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* channelId at 311 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* nonStandard at 312 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ChannelJoinConfirm_specs_1 = {
	sizeof(struct ChannelJoinConfirm),
	offsetof(struct ChannelJoinConfirm, _asn_ctx),
	asn_MAP_ChannelJoinConfirm_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ChannelJoinConfirm_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ChannelJoinConfirm = {
	"ChannelJoinConfirm",
	"ChannelJoinConfirm",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ChannelJoinConfirm_tags_1,
	sizeof(asn_DEF_ChannelJoinConfirm_tags_1)
		/sizeof(asn_DEF_ChannelJoinConfirm_tags_1[0]), /* 1 */
	asn_DEF_ChannelJoinConfirm_tags_1,	/* Same as above */
	sizeof(asn_DEF_ChannelJoinConfirm_tags_1)
		/sizeof(asn_DEF_ChannelJoinConfirm_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ChannelJoinConfirm_1,
	5,	/* Elements count */
	&asn_SPC_ChannelJoinConfirm_specs_1	/* Additional specs */
};

