/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_ChannelId_H_
#define	_ChannelId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ChannelId */
typedef long	 ChannelId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChannelId;
asn_struct_free_f ChannelId_free;
asn_struct_print_f ChannelId_print;
asn_constr_check_f ChannelId_constraint;
ber_type_decoder_f ChannelId_decode_ber;
der_type_encoder_f ChannelId_encode_der;
xer_type_decoder_f ChannelId_decode_xer;
xer_type_encoder_f ChannelId_encode_xer;
per_type_decoder_f ChannelId_decode_uper;
per_type_encoder_f ChannelId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ChannelId_H_ */
