/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_DataPriority_H_
#define	_DataPriority_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DataPriority_PR {
	DataPriority_PR_NOTHING,	/* No components present */
	DataPriority_PR_top,
	DataPriority_PR_high,
	DataPriority_PR_medium,
	DataPriority_PR_low,
	/* Extensions may appear below */
	
} DataPriority_PR;

/* DataPriority */
typedef struct DataPriority {
	DataPriority_PR present;
	union DataPriority_u {
		NULL_t	 top;
		NULL_t	 high;
		NULL_t	 medium;
		NULL_t	 low;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataPriority_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataPriority;

#ifdef __cplusplus
}
#endif

#endif	/* _DataPriority_H_ */
