/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#include <asn_internal.h>

#include "Diagnostic.h"

static asn_per_constraints_t asn_PER_type_Diagnostic_constr_1 = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  13 }	/* (0..13,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Diagnostic_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_inconsistent_merge),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-inconsistent-merge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_forbidden_PDU_downward),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-forbidden-PDU-downward"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_forbidden_PDU_upward),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-forbidden-PDU-upward"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_invalid_BER_encoding),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-invalid-BER-encoding"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_invalid_PER_encoding),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-invalid-PER-encoding"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_misrouted_user),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-misrouted-user"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_unrequested_confirm),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-unrequested-confirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_wrong_transport_priority),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-wrong-transport-priority"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_channel_id_conflict),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-channel-id-conflict"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_token_id_conflict),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-token-id-conflict"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_not_user_id_channel),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-not-user-id-channel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_too_many_channels),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-too-many-channels"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_too_many_tokens),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-too-many-tokens"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostic, choice.dc_too_many_users),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dc-too-many-users"
		},
};
static asn_TYPE_tag2member_t asn_MAP_Diagnostic_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dc-inconsistent-merge at 669 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dc-forbidden-PDU-downward at 670 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dc-forbidden-PDU-upward at 671 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* dc-invalid-BER-encoding at 672 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* dc-invalid-PER-encoding at 673 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* dc-misrouted-user at 674 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* dc-unrequested-confirm at 675 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* dc-wrong-transport-priority at 676 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* dc-channel-id-conflict at 677 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* dc-token-id-conflict at 678 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* dc-not-user-id-channel at 679 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* dc-too-many-channels at 680 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* dc-too-many-tokens at 681 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 } /* dc-too-many-users at 682 */
};
static asn_CHOICE_specifics_t asn_SPC_Diagnostic_specs_1 = {
	sizeof(struct Diagnostic),
	offsetof(struct Diagnostic, _asn_ctx),
	offsetof(struct Diagnostic, present),
	sizeof(((struct Diagnostic *)0)->present),
	asn_MAP_Diagnostic_tag2el_1,
	14,	/* Count of tags in the map */
	0,
	14	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Diagnostic = {
	"Diagnostic",
	"Diagnostic",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_Diagnostic_constr_1,
	asn_MBR_Diagnostic_1,
	14,	/* Elements count */
	&asn_SPC_Diagnostic_specs_1	/* Additional specs */
};

