/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_DomainMCSPDU_H_
#define	_DomainMCSPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PlumbDomainIndication.h"
#include "ErectDomainRequest.h"
#include "MergeChannelsRequest.h"
#include "MergeChannelsConfirm.h"
#include "PurgeChannelsIndication.h"
#include "MergeTokensRequest.h"
#include "MergeTokensConfirm.h"
#include "PurgeTokensIndication.h"
#include "DisconnectProviderUltimatum.h"
#include "RejectMCSPDUUltimatum.h"
#include "AttachUserRequest.h"
#include "AttachUserConfirm.h"
#include "DetachUserRequest.h"
#include "DetachUserIndication.h"
#include "ChannelJoinRequest.h"
#include "ChannelJoinConfirm.h"
#include "ChannelLeaveRequest.h"
#include "ChannelConveneRequest.h"
#include "ChannelConveneConfirm.h"
#include "ChannelDisbandRequest.h"
#include "ChannelDisbandIndication.h"
#include "ChannelAdmitRequest.h"
#include "ChannelAdmitIndication.h"
#include "ChannelExpelRequest.h"
#include "ChannelExpelIndication.h"
#include "SendDataRequest.h"
#include "SendDataIndication.h"
#include "UniformSendDataRequest.h"
#include "UniformSendDataIndication.h"
#include "TokenGrabRequest.h"
#include "TokenGrabConfirm.h"
#include "TokenInhibitRequest.h"
#include "TokenInhibitConfirm.h"
#include "TokenGiveRequest.h"
#include "TokenGiveIndication.h"
#include "TokenGiveResponse.h"
#include "TokenGiveConfirm.h"
#include "TokenPleaseRequest.h"
#include "TokenPleaseIndication.h"
#include "TokenReleaseRequest.h"
#include "TokenReleaseConfirm.h"
#include "TokenTestRequest.h"
#include "TokenTestConfirm.h"
#include "NonStandardPDU.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DomainMCSPDU_PR {
	DomainMCSPDU_PR_NOTHING,	/* No components present */
	DomainMCSPDU_PR_plumbDomainIndication,
	DomainMCSPDU_PR_erectDomainRequest,
	DomainMCSPDU_PR_mergeChannelsRequest,
	DomainMCSPDU_PR_mergeChannelsConfirm,
	DomainMCSPDU_PR_purgeChannelsIndication,
	DomainMCSPDU_PR_mergeTokensRequest,
	DomainMCSPDU_PR_mergeTokensConfirm,
	DomainMCSPDU_PR_purgeTokensIndication,
	DomainMCSPDU_PR_disconnectProviderUltimatum,
	DomainMCSPDU_PR_rejectMCSPDUUltimatum,
	DomainMCSPDU_PR_attachUserRequest,
	DomainMCSPDU_PR_attachUserConfirm,
	DomainMCSPDU_PR_detachUserRequest,
	DomainMCSPDU_PR_detachUserIndication,
	DomainMCSPDU_PR_channelJoinRequest,
	DomainMCSPDU_PR_channelJoinConfirm,
	DomainMCSPDU_PR_channelLeaveRequest,
	DomainMCSPDU_PR_channelConveneRequest,
	DomainMCSPDU_PR_channelConveneConfirm,
	DomainMCSPDU_PR_channelDisbandRequest,
	DomainMCSPDU_PR_channelDisbandIndication,
	DomainMCSPDU_PR_channelAdmitRequest,
	DomainMCSPDU_PR_channelAdmitIndication,
	DomainMCSPDU_PR_channelExpelRequest,
	DomainMCSPDU_PR_channelExpelIndication,
	DomainMCSPDU_PR_sendDataRequest,
	DomainMCSPDU_PR_sendDataIndication,
	DomainMCSPDU_PR_uniformSendDataRequest,
	DomainMCSPDU_PR_uniformSendDataIndication,
	DomainMCSPDU_PR_tokenGrabRequest,
	DomainMCSPDU_PR_tokenGrabConfirm,
	DomainMCSPDU_PR_tokenInhibitRequest,
	DomainMCSPDU_PR_tokenInhibitConfirm,
	DomainMCSPDU_PR_tokenGiveRequest,
	DomainMCSPDU_PR_tokenGiveIndication,
	DomainMCSPDU_PR_tokenGiveResponse,
	DomainMCSPDU_PR_tokenGiveConfirm,
	DomainMCSPDU_PR_tokenPleaseRequest,
	DomainMCSPDU_PR_tokenPleaseIndication,
	DomainMCSPDU_PR_tokenReleaseRequest,
	DomainMCSPDU_PR_tokenReleaseConfirm,
	DomainMCSPDU_PR_tokenTestRequest,
	DomainMCSPDU_PR_tokenTestConfirm,
	DomainMCSPDU_PR_nonStandard,
	/* Extensions may appear below */
	
} DomainMCSPDU_PR;

/* DomainMCSPDU */
typedef struct DomainMCSPDU {
	DomainMCSPDU_PR present;
	union DomainMCSPDU_u {
		PlumbDomainIndication_t	 plumbDomainIndication;
		ErectDomainRequest_t	 erectDomainRequest;
		MergeChannelsRequest_t	 mergeChannelsRequest;
		MergeChannelsConfirm_t	 mergeChannelsConfirm;
		PurgeChannelsIndication_t	 purgeChannelsIndication;
		MergeTokensRequest_t	 mergeTokensRequest;
		MergeTokensConfirm_t	 mergeTokensConfirm;
		PurgeTokensIndication_t	 purgeTokensIndication;
		DisconnectProviderUltimatum_t	 disconnectProviderUltimatum;
		RejectMCSPDUUltimatum_t	 rejectMCSPDUUltimatum;
		AttachUserRequest_t	 attachUserRequest;
		AttachUserConfirm_t	 attachUserConfirm;
		DetachUserRequest_t	 detachUserRequest;
		DetachUserIndication_t	 detachUserIndication;
		ChannelJoinRequest_t	 channelJoinRequest;
		ChannelJoinConfirm_t	 channelJoinConfirm;
		ChannelLeaveRequest_t	 channelLeaveRequest;
		ChannelConveneRequest_t	 channelConveneRequest;
		ChannelConveneConfirm_t	 channelConveneConfirm;
		ChannelDisbandRequest_t	 channelDisbandRequest;
		ChannelDisbandIndication_t	 channelDisbandIndication;
		ChannelAdmitRequest_t	 channelAdmitRequest;
		ChannelAdmitIndication_t	 channelAdmitIndication;
		ChannelExpelRequest_t	 channelExpelRequest;
		ChannelExpelIndication_t	 channelExpelIndication;
		SendDataRequest_t	 sendDataRequest;
		SendDataIndication_t	 sendDataIndication;
		UniformSendDataRequest_t	 uniformSendDataRequest;
		UniformSendDataIndication_t	 uniformSendDataIndication;
		TokenGrabRequest_t	 tokenGrabRequest;
		TokenGrabConfirm_t	 tokenGrabConfirm;
		TokenInhibitRequest_t	 tokenInhibitRequest;
		TokenInhibitConfirm_t	 tokenInhibitConfirm;
		TokenGiveRequest_t	 tokenGiveRequest;
		TokenGiveIndication_t	 tokenGiveIndication;
		TokenGiveResponse_t	 tokenGiveResponse;
		TokenGiveConfirm_t	 tokenGiveConfirm;
		TokenPleaseRequest_t	 tokenPleaseRequest;
		TokenPleaseIndication_t	 tokenPleaseIndication;
		TokenReleaseRequest_t	 tokenReleaseRequest;
		TokenReleaseConfirm_t	 tokenReleaseConfirm;
		TokenTestRequest_t	 tokenTestRequest;
		TokenTestConfirm_t	 tokenTestConfirm;
		NonStandardPDU_t	 nonStandard;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DomainMCSPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DomainMCSPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _DomainMCSPDU_H_ */
