/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#include <asn_internal.h>

#include "ErectDomainRequest.h"

static int
memb_subHeight_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_subInterval_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_subHeight_constr_2 = {
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (0..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_subInterval_constr_3 = {
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (0..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_nonStandard_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NonStandardParameter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_nonStandard_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nonStandard_specs_4 = {
	sizeof(struct ErectDomainRequest__nonStandard),
	offsetof(struct ErectDomainRequest__nonStandard, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonStandard_4 = {
	"nonStandard",
	"nonStandard",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonStandard_tags_4,
	sizeof(asn_DEF_nonStandard_tags_4)
		/sizeof(asn_DEF_nonStandard_tags_4[0]) - 1, /* 1 */
	asn_DEF_nonStandard_tags_4,	/* Same as above */
	sizeof(asn_DEF_nonStandard_tags_4)
		/sizeof(asn_DEF_nonStandard_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_nonStandard_4,
	1,	/* Single element */
	&asn_SPC_nonStandard_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ErectDomainRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ErectDomainRequest, subHeight),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_subHeight_constraint_1,
		&asn_PER_memb_subHeight_constr_2,
		0,
		"subHeight"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ErectDomainRequest, subInterval),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_subInterval_constraint_1,
		&asn_PER_memb_subInterval_constr_3,
		0,
		"subInterval"
		},
	{ ATF_POINTER, 1, offsetof(struct ErectDomainRequest, nonStandard),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_nonStandard_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonStandard"
		},
};
static int asn_MAP_ErectDomainRequest_oms_1[] = { 2 };
static ber_tlv_tag_t asn_DEF_ErectDomainRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ErectDomainRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* subHeight at 109 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* subInterval at 111 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* nonStandard at 113 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ErectDomainRequest_specs_1 = {
	sizeof(struct ErectDomainRequest),
	offsetof(struct ErectDomainRequest, _asn_ctx),
	asn_MAP_ErectDomainRequest_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ErectDomainRequest_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ErectDomainRequest = {
	"ErectDomainRequest",
	"ErectDomainRequest",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ErectDomainRequest_tags_1,
	sizeof(asn_DEF_ErectDomainRequest_tags_1)
		/sizeof(asn_DEF_ErectDomainRequest_tags_1[0]), /* 1 */
	asn_DEF_ErectDomainRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_ErectDomainRequest_tags_1)
		/sizeof(asn_DEF_ErectDomainRequest_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ErectDomainRequest_1,
	3,	/* Elements count */
	&asn_SPC_ErectDomainRequest_specs_1	/* Additional specs */
};

