/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#include <asn_internal.h>

#include "ExtendedParameterMCSPDU.h"

static asn_per_constraints_t asn_PER_type_ExtendedParameterMCSPDU_constr_1 = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ExtendedParameterMCSPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ExtendedParameterMCSPDU, choice.extendedParameterPropose),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtendedParameterPropose,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"extendedParameterPropose"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ExtendedParameterMCSPDU, choice.extendedParameterAccept),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtendedParameterAccept,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"extendedParameterAccept"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ExtendedParameterMCSPDU, choice.nonStandard),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NonStandardPDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonStandard"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ExtendedParameterMCSPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* extendedParameterPropose at 696 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* extendedParameterAccept at 697 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* nonStandard at 698 */
};
static asn_CHOICE_specifics_t asn_SPC_ExtendedParameterMCSPDU_specs_1 = {
	sizeof(struct ExtendedParameterMCSPDU),
	offsetof(struct ExtendedParameterMCSPDU, _asn_ctx),
	offsetof(struct ExtendedParameterMCSPDU, present),
	sizeof(((struct ExtendedParameterMCSPDU *)0)->present),
	asn_MAP_ExtendedParameterMCSPDU_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ExtendedParameterMCSPDU = {
	"ExtendedParameterMCSPDU",
	"ExtendedParameterMCSPDU",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_ExtendedParameterMCSPDU_constr_1,
	asn_MBR_ExtendedParameterMCSPDU_1,
	3,	/* Elements count */
	&asn_SPC_ExtendedParameterMCSPDU_specs_1	/* Additional specs */
};

