/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_Key_H_
#define	_Key_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include "H221NonStandardIdentifier.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Key_PR {
	Key_PR_NOTHING,	/* No components present */
	Key_PR_object,
	Key_PR_h221NonStandard
} Key_PR;

/* Key */
typedef struct Key {
	Key_PR present;
	union Key_u {
		OBJECT_IDENTIFIER_t	 object;
		H221NonStandardIdentifier_t	 h221NonStandard;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Key_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Key;

#ifdef __cplusplus
}
#endif

#endif	/* _Key_H_ */
