/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_MergeChannelsConfirm_H_
#define	_MergeChannelsConfirm_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include "ChannelId.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChannelAttributes;
struct NonStandardParameter;

/* MergeChannelsConfirm */
typedef struct MergeChannelsConfirm {
	struct MergeChannelsConfirm__mergeChannels {
		A_SET_OF(struct ChannelAttributes) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} mergeChannels;
	struct MergeChannelsConfirm__purgeChannelIds {
		A_SET_OF(ChannelId_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} purgeChannelIds;
	struct MergeChannelsConfirm__nonStandard {
		A_SEQUENCE_OF(struct NonStandardParameter) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonStandard;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MergeChannelsConfirm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MergeChannelsConfirm;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChannelAttributes.h"
#include "NonStandardParameter.h"

#endif	/* _MergeChannelsConfirm_H_ */
