/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#include <asn_internal.h>

#include "NonStandardParameter.h"

static asn_TYPE_member_t asn_MBR_NonStandardParameter_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NonStandardParameter, key),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Key,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"key"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NonStandardParameter, data),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"data"
		},
};
static ber_tlv_tag_t asn_DEF_NonStandardParameter_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_NonStandardParameter_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* key at 22 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* data at 23 */
};
static asn_SEQUENCE_specifics_t asn_SPC_NonStandardParameter_specs_1 = {
	sizeof(struct NonStandardParameter),
	offsetof(struct NonStandardParameter, _asn_ctx),
	asn_MAP_NonStandardParameter_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_NonStandardParameter = {
	"NonStandardParameter",
	"NonStandardParameter",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_NonStandardParameter_tags_1,
	sizeof(asn_DEF_NonStandardParameter_tags_1)
		/sizeof(asn_DEF_NonStandardParameter_tags_1[0]), /* 1 */
	asn_DEF_NonStandardParameter_tags_1,	/* Same as above */
	sizeof(asn_DEF_NonStandardParameter_tags_1)
		/sizeof(asn_DEF_NonStandardParameter_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_NonStandardParameter_1,
	2,	/* Elements count */
	&asn_SPC_NonStandardParameter_specs_1	/* Additional specs */
};

