/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_NonStandardParameter_H_
#define	_NonStandardParameter_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Key.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NonStandardParameter */
typedef struct NonStandardParameter {
	Key_t	 key;
	OCTET_STRING_t	 data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NonStandardParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NonStandardParameter;

#ifdef __cplusplus
}
#endif

#endif	/* _NonStandardParameter_H_ */
