/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_NonStandardPDU_H_
#define	_NonStandardPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NonStandardParameter.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NonStandardPDU */
typedef struct NonStandardPDU {
	NonStandardParameter_t	 data;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NonStandardPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NonStandardPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _NonStandardPDU_H_ */
