/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_ParticipationIndicator_H_
#define	_ParticipationIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ParticipationIndicator_PR {
	ParticipationIndicator_PR_NOTHING,	/* No components present */
	ParticipationIndicator_PR_global,
	ParticipationIndicator_PR_partial
} ParticipationIndicator_PR;

/* ParticipationIndicator */
typedef struct ParticipationIndicator {
	ParticipationIndicator_PR present;
	union ParticipationIndicator_u {
		NULL_t	 global;
		long	 partial;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParticipationIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParticipationIndicator;

#ifdef __cplusplus
}
#endif

#endif	/* _ParticipationIndicator_H_ */
