/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_Segmentation_H_
#define	_Segmentation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Segmentation {
	Segmentation_begin	= 0,
	Segmentation_end	= 1
} e_Segmentation;

/* Segmentation */
typedef BIT_STRING_t	 Segmentation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Segmentation;
asn_struct_free_f Segmentation_free;
asn_struct_print_f Segmentation_print;
asn_constr_check_f Segmentation_constraint;
ber_type_decoder_f Segmentation_decode_ber;
der_type_encoder_f Segmentation_encode_der;
xer_type_decoder_f Segmentation_decode_xer;
xer_type_encoder_f Segmentation_encode_xer;
per_type_decoder_f Segmentation_decode_uper;
per_type_encoder_f Segmentation_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Segmentation_H_ */
