/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_SendDataRequest_H_
#define	_SendDataRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UserId.h"
#include "ChannelId.h"
#include <BOOLEAN.h>
#include <NativeInteger.h>
#include "DataPriority.h"
#include "Segmentation.h"
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NonStandardParameter;

/* SendDataRequest */
typedef struct SendDataRequest {
	UserId_t	 initiator;
	ChannelId_t	 channelId;
	BOOLEAN_t	 reliability;
	long	*domainReferenceID	/* OPTIONAL */;
	DataPriority_t	 dataPriority;
	Segmentation_t	 segmentation;
	OCTET_STRING_t	 userData;
	long	*totalDataSize	/* OPTIONAL */;
	struct SendDataRequest__nonStandard {
		A_SEQUENCE_OF(struct NonStandardParameter) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonStandard;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SendDataRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SendDataRequest;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NonStandardParameter.h"

#endif	/* _SendDataRequest_H_ */
