/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_SeqOfRequestCapabilities_H_
#define	_SeqOfRequestCapabilities_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RequestCapability;

/* SeqOfRequestCapabilities */
typedef struct SeqOfRequestCapabilities {
	A_SEQUENCE_OF(struct RequestCapability) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SeqOfRequestCapabilities_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SeqOfRequestCapabilities;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RequestCapability.h"

#endif	/* _SeqOfRequestCapabilities_H_ */
