/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_StaticChannelId_H_
#define	_StaticChannelId_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ChannelId.h"

#ifdef __cplusplus
extern "C" {
#endif

/* StaticChannelId */
typedef ChannelId_t	 StaticChannelId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StaticChannelId;
asn_struct_free_f StaticChannelId_free;
asn_struct_print_f StaticChannelId_print;
asn_constr_check_f StaticChannelId_constraint;
ber_type_decoder_f StaticChannelId_decode_ber;
der_type_encoder_f StaticChannelId_encode_der;
xer_type_decoder_f StaticChannelId_decode_xer;
xer_type_encoder_f StaticChannelId_encode_xer;
per_type_decoder_f StaticChannelId_decode_uper;
per_type_encoder_f StaticChannelId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _StaticChannelId_H_ */
