/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#include <asn_internal.h>

#include "TokenGiveResponse.h"

static asn_TYPE_member_t asn_MBR_nonStandard_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NonStandardParameter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_nonStandard_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nonStandard_specs_5 = {
	sizeof(struct TokenGiveResponse__nonStandard),
	offsetof(struct TokenGiveResponse__nonStandard, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonStandard_5 = {
	"nonStandard",
	"nonStandard",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonStandard_tags_5,
	sizeof(asn_DEF_nonStandard_tags_5)
		/sizeof(asn_DEF_nonStandard_tags_5[0]) - 1, /* 1 */
	asn_DEF_nonStandard_tags_5,	/* Same as above */
	sizeof(asn_DEF_nonStandard_tags_5)
		/sizeof(asn_DEF_nonStandard_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_nonStandard_5,
	1,	/* Single element */
	&asn_SPC_nonStandard_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_TokenGiveResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TokenGiveResponse, result),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Result,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"result"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TokenGiveResponse, recipient),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UserId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"recipient"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TokenGiveResponse, tokenId),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TokenId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tokenId"
		},
	{ ATF_POINTER, 1, offsetof(struct TokenGiveResponse, nonStandard),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_nonStandard_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonStandard"
		},
};
static int asn_MAP_TokenGiveResponse_oms_1[] = { 3 };
static ber_tlv_tag_t asn_DEF_TokenGiveResponse_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TokenGiveResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* result at 504 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* recipient at 505 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* tokenId at 506 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* nonStandard at 507 */
};
static asn_SEQUENCE_specifics_t asn_SPC_TokenGiveResponse_specs_1 = {
	sizeof(struct TokenGiveResponse),
	offsetof(struct TokenGiveResponse, _asn_ctx),
	asn_MAP_TokenGiveResponse_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_TokenGiveResponse_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TokenGiveResponse = {
	"TokenGiveResponse",
	"TokenGiveResponse",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TokenGiveResponse_tags_1,
	sizeof(asn_DEF_TokenGiveResponse_tags_1)
		/sizeof(asn_DEF_TokenGiveResponse_tags_1[0]), /* 1 */
	asn_DEF_TokenGiveResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_TokenGiveResponse_tags_1)
		/sizeof(asn_DEF_TokenGiveResponse_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TokenGiveResponse_1,
	4,	/* Elements count */
	&asn_SPC_TokenGiveResponse_specs_1	/* Additional specs */
};

