/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#include <asn_internal.h>

#include "TokenReleaseConfirm.h"

static asn_TYPE_member_t asn_MBR_nonStandard_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NonStandardParameter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_nonStandard_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nonStandard_specs_6 = {
	sizeof(struct TokenReleaseConfirm__nonStandard),
	offsetof(struct TokenReleaseConfirm__nonStandard, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonStandard_6 = {
	"nonStandard",
	"nonStandard",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonStandard_tags_6,
	sizeof(asn_DEF_nonStandard_tags_6)
		/sizeof(asn_DEF_nonStandard_tags_6[0]) - 1, /* 1 */
	asn_DEF_nonStandard_tags_6,	/* Same as above */
	sizeof(asn_DEF_nonStandard_tags_6)
		/sizeof(asn_DEF_nonStandard_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_nonStandard_6,
	1,	/* Single element */
	&asn_SPC_nonStandard_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_TokenReleaseConfirm_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TokenReleaseConfirm, result),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Result,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"result"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TokenReleaseConfirm, initiator),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UserId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"initiator"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TokenReleaseConfirm, tokenId),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TokenId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tokenId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TokenReleaseConfirm, tokenStatus),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TokenStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tokenStatus"
		},
	{ ATF_POINTER, 1, offsetof(struct TokenReleaseConfirm, nonStandard),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_nonStandard_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonStandard"
		},
};
static int asn_MAP_TokenReleaseConfirm_oms_1[] = { 4 };
static ber_tlv_tag_t asn_DEF_TokenReleaseConfirm_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TokenReleaseConfirm_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* result at 547 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* initiator at 548 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* tokenId at 549 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* tokenStatus at 550 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* nonStandard at 551 */
};
static asn_SEQUENCE_specifics_t asn_SPC_TokenReleaseConfirm_specs_1 = {
	sizeof(struct TokenReleaseConfirm),
	offsetof(struct TokenReleaseConfirm, _asn_ctx),
	asn_MAP_TokenReleaseConfirm_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_TokenReleaseConfirm_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TokenReleaseConfirm = {
	"TokenReleaseConfirm",
	"TokenReleaseConfirm",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TokenReleaseConfirm_tags_1,
	sizeof(asn_DEF_TokenReleaseConfirm_tags_1)
		/sizeof(asn_DEF_TokenReleaseConfirm_tags_1[0]), /* 1 */
	asn_DEF_TokenReleaseConfirm_tags_1,	/* Same as above */
	sizeof(asn_DEF_TokenReleaseConfirm_tags_1)
		/sizeof(asn_DEF_TokenReleaseConfirm_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TokenReleaseConfirm_1,
	5,	/* Elements count */
	&asn_SPC_TokenReleaseConfirm_specs_1	/* Additional specs */
};

