/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#ifndef	_TokenId_H_
#define	_TokenId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TokenId */
typedef long	 TokenId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TokenId;
asn_struct_free_f TokenId_free;
asn_struct_print_f TokenId_print;
asn_constr_check_f TokenId_constraint;
ber_type_decoder_f TokenId_decode_ber;
der_type_encoder_f TokenId_encode_der;
xer_type_decoder_f TokenId_decode_xer;
xer_type_encoder_f TokenId_encode_xer;
per_type_decoder_f TokenId_decode_uper;
per_type_encoder_f TokenId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TokenId_H_ */
