/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "MCS-PROTOCOL-3"
 * 	found in "mcs.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names -gen-PER`
 */

#include <asn_internal.h>

#include "UniformSendDataIndication.h"

static int
memb_domainReferenceID_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_domainReferenceID_constr_5 = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_nonStandard_10[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NonStandardParameter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_nonStandard_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nonStandard_specs_10 = {
	sizeof(struct UniformSendDataIndication__nonStandard),
	offsetof(struct UniformSendDataIndication__nonStandard, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonStandard_10 = {
	"nonStandard",
	"nonStandard",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonStandard_tags_10,
	sizeof(asn_DEF_nonStandard_tags_10)
		/sizeof(asn_DEF_nonStandard_tags_10[0]) - 1, /* 1 */
	asn_DEF_nonStandard_tags_10,	/* Same as above */
	sizeof(asn_DEF_nonStandard_tags_10)
		/sizeof(asn_DEF_nonStandard_tags_10[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_nonStandard_10,
	1,	/* Single element */
	&asn_SPC_nonStandard_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_UniformSendDataIndication_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UniformSendDataIndication, initiator),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UserId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"initiator"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UniformSendDataIndication, channelId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChannelId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"channelId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UniformSendDataIndication, reliability),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reliability"
		},
	{ ATF_POINTER, 1, offsetof(struct UniformSendDataIndication, domainReferenceID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_domainReferenceID_constraint_1,
		&asn_PER_memb_domainReferenceID_constr_5,
		0,
		"domainReferenceID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UniformSendDataIndication, dataPriority),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_DataPriority,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dataPriority"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UniformSendDataIndication, segmentation),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Segmentation,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"segmentation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UniformSendDataIndication, userData),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"userData"
		},
	{ ATF_POINTER, 2, offsetof(struct UniformSendDataIndication, totalDataSize),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"totalDataSize"
		},
	{ ATF_POINTER, 1, offsetof(struct UniformSendDataIndication, nonStandard),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		0,
		&asn_DEF_nonStandard_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonStandard"
		},
};
static int asn_MAP_UniformSendDataIndication_oms_1[] = { 3, 7, 8 };
static ber_tlv_tag_t asn_DEF_UniformSendDataIndication_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_UniformSendDataIndication_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* initiator at 434 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* channelId at 435 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* reliability at 436 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* domainReferenceID at 437 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* dataPriority at 438 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* segmentation at 439 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* userData at 440 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* totalDataSize at 441 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* nonStandard at 442 */
};
static asn_SEQUENCE_specifics_t asn_SPC_UniformSendDataIndication_specs_1 = {
	sizeof(struct UniformSendDataIndication),
	offsetof(struct UniformSendDataIndication, _asn_ctx),
	asn_MAP_UniformSendDataIndication_tag2el_1,
	9,	/* Count of tags in the map */
	asn_MAP_UniformSendDataIndication_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	8,	/* Start extensions */
	10	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_UniformSendDataIndication = {
	"UniformSendDataIndication",
	"UniformSendDataIndication",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_UniformSendDataIndication_tags_1,
	sizeof(asn_DEF_UniformSendDataIndication_tags_1)
		/sizeof(asn_DEF_UniformSendDataIndication_tags_1[0]), /* 1 */
	asn_DEF_UniformSendDataIndication_tags_1,	/* Same as above */
	sizeof(asn_DEF_UniformSendDataIndication_tags_1)
		/sizeof(asn_DEF_UniformSendDataIndication_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_UniformSendDataIndication_1,
	9,	/* Elements count */
	&asn_SPC_UniformSendDataIndication_specs_1	/* Additional specs */
};

